#!/usr/bin/env python3
"""
AutoResearch-style parameter tuner for FluidAudio speaker diarization.

Iterates through parameter combinations, rebuilds, runs diarization,
evaluates against ground-truth speaker sequence, and reports the best config.

Ground truth speaker sequence (from the correct transcript):
  S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S1 → S2 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1 → S2 → S1

Evaluated on:
- Speaker count (exactly 2 → +40 pts, 1 → 0 pts, 3+ → 10 pts)
- Speaker balance (both >20% of time → +20 pts)
- Segment count (within 30-80% of ground truth count → +20 pts)
- Sequence match (Damerau-Levenshtein similarity to ground truth → +20 pts)
"""

import json
import math
import os
import re
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Tuple

# ── Ground truth (speaker sequence from the corrected transcript) ────
GROUND_TRUTH_SEQ = [
    "S1", "S2", "S1", "S2", "S1", "S2", "S1", "S2", "S1", "S2",
    "S1", "S2", "S1", "S2", "S1", "S2", "S1", "S2", "S1", "S2",
    "S1", "S1", "S2", "S2", "S1", "S2", "S1", "S2", "S1", "S2",
    "S1", "S2", "S1", "S2", "S1", "S2", "S1", "S2", "S1", "S2",
    "S1", "S2", "S1", "S2", "S1",
]
GT_COUNT = len(GROUND_TRUTH_SEQ)

AUDIO_FILE = "/Users/yanhui/Documents/空杯心态与AI时代的自我刷新.wav"
PROJECT_DIR = "/tmp/ohr"
DIARIZER_SWIFT = os.path.join(PROJECT_DIR, "Sources", "Diarizer.swift")
BINARY = os.path.join(PROJECT_DIR, ".build", "release", "ohr")

# ── Parameter search space ───────────────────────────────────────────
# The key parameters that affect speaker separation quality.
# Each entry: (param_name, values, swift_code_template)
# Templates use {value} as placeholder.

PARAM_GRID = {
    "clustering_threshold": [0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70],
    "embedding_minSegmentDuration": [0.3, 0.5, 0.7, 1.0],
    "segmentation_minDurationOn": [0.0, 0.1, 0.2, 0.3],
    "segmentation_minDurationOff": [0.0, 0.1, 0.2, 0.3],
    "segmentation_speechOnsetThreshold": [0.4, 0.5, 0.6],
    "segmentation_speechOffsetThreshold": [0.4, 0.5, 0.6],
    "postProcessing_minGap": [0.02, 0.05, 0.1],
    "segmentation_stepRatio": [0.15, 0.2, 0.3],
    "clustering_warmStartFa": [0.04, 0.07, 0.1],
    "clustering_warmStartFb": [0.7, 0.8, 0.9],
}


@dataclass
class TuneResult:
    params: dict
    speaker_count: int = 0
    segments: List[Tuple[str, float, float]] = field(default_factory=list)
    seq: List[str] = field(default_factory=list)
    balance_s1: float = 0.0
    balance_s2: float = 0.0
    score: float = 0.0
    details: str = ""
    build_time: float = 0.0
    run_time: float = 0.0


# ── Config template ──────────────────────────────────────────────────

CONFIG_TEMPLATE = """// Auto-generated by tune.py — do not edit manually
func defaultDiarizerConfig() -> OfflineDiarizerConfig {{
    OfflineDiarizerConfig(
        segmentation: .init(
            windowDurationSeconds: {seg_window_duration},
            sampleRate: 16_000,
            minDurationOn: {seg_min_duration_on},
            minDurationOff: {seg_min_duration_off},
            stepRatio: {seg_step_ratio},
            speechOnsetThreshold: Float({seg_speech_onset_threshold}),
            speechOffsetThreshold: Float({seg_speech_offset_threshold})
        ),
        embedding: .init(
            batchSize: 32,
            excludeOverlap: true,
            minSegmentDurationSeconds: {emb_min_segment_duration},
            skipStrategy: .none
        ),
        clustering: .init(
            threshold: {clus_threshold},
            warmStartFa: {clus_warm_start_fa},
            warmStartFb: {clus_warm_start_fb},
            numSpeakers: 2
        ),
        postProcessing: .init(
            minGapDurationSeconds: {post_min_gap},
            exclusiveSegments: true
        ),
        zeroVoteReembed: .init(
            enabled: true,
            minDurationSeconds: 0.4
        ),
        exposeChunkEmbeddings: false
    )
}}
"""


def build_config(params: dict) -> str:
    """Generate the Swift config function body from a parameter dict."""
    return CONFIG_TEMPLATE.format(
        seg_window_duration=10.0,
        seg_min_duration_on=params["segmentation_minDurationOn"],
        seg_min_duration_off=params["segmentation_minDurationOff"],
        seg_step_ratio=params["segmentation_stepRatio"],
        seg_speech_onset_threshold=params["segmentation_speechOnsetThreshold"],
        seg_speech_offset_threshold=params["segmentation_speechOffsetThreshold"],
        emb_min_segment_duration=params["embedding_minSegmentDuration"],
        clus_threshold=params["clustering_threshold"],
        clus_warm_start_fa=params["clustering_warmStartFa"],
        clus_warm_start_fb=params["clustering_warmStartFb"],
        post_min_gap=params["postProcessing_minGap"],
    )


def write_diarizer_swift(config_body: str) -> None:
    """Write the modified Diarizer.swift with the given config body."""
    # Read the current file
    with open(DIARIZER_SWIFT, "r") as f:
        content = f.read()

    # Replace the defaultDiarizerConfig function body
    # Find the function start and end
    start_marker = "func defaultDiarizerConfig() -> OfflineDiarizerConfig {"
    end_marker = "\nfunc runDiarization"

    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker, start_idx)

    if start_idx == -1 or end_idx == -1:
        print("ERROR: Could not find defaultDiarizerConfig in Diarizer.swift")
        sys.exit(1)

    new_content = content[:start_idx] + config_body + content[end_idx:]

    with open(DIARIZER_SWIFT, "w") as f:
        f.write(new_content)


def build_project() -> float:
    """Rebuild the project. Returns build time in seconds."""
    start = time.time()
    result = subprocess.run(
        ["swift", "build", "-c", "release"],
        cwd=PROJECT_DIR,
        capture_output=True,
        text=True,
        timeout=300,
        env={**os.environ, "DEVELOPER_DIR": "/Applications/Xcode-beta.app/Contents/Developer"}
    )
    elapsed = time.time() - start
    if result.returncode != 0:
        print(f"  BUILD FAILED ({elapsed:.1f}s)")
        print(result.stderr[-500:] if result.stderr else "")
        return -1
    return elapsed


def run_diarization() -> Optional[str]:
    """Run diarization and return the raw output text, or None on failure."""
    start = time.time()
    result = subprocess.run(
        [BINARY, "--speakers", "-q", AUDIO_FILE],
        capture_output=True,
        text=True,
        timeout=600,
    )
    elapsed = time.time() - start
    if result.returncode != 0:
        print(f"  RUN FAILED ({elapsed:.1f}s): {result.stderr[:200]}")
        return None
    return result.stdout


def parse_diarization_output(text: str) -> TuneResult:
    """Parse the diarization output and extract evaluation metrics."""
    result = TuneResult(params={})

    # Parse segments: 【S1】 or 【S2】 followed by text
    segments = []
    current_speaker = None
    current_lines = []

    for line in text.split("\n"):
        if line.startswith("【"):
            # Save previous segment
            if current_speaker is not None:
                for seg_text in current_lines:
                    segments.append((current_speaker, seg_text))

            # Parse new speaker
            match = re.match(r"【(S\d+)】", line)
            if match:
                current_speaker = match.group(1)
                remaining = line[match.end():].strip()
                current_lines = [remaining] if remaining else []
            else:
                current_speaker = None
                current_lines = []
        elif current_speaker is not None:
            stripped = line.strip()
            if stripped:
                current_lines.append(stripped)

    # Don't forget the last segment
    if current_speaker is not None and current_lines:
        for seg_text in current_lines:
            segments.append((current_speaker, seg_text))

    # Also try to parse the output format that shows segments with timestamps
    # If no segments found via the 【S1】 format, try the raw text
    if not segments:
        # The output might be just one block of text with a single speaker prefix
        if text.strip().startswith("【"):
            first_line = text.strip().split("\n")[0]
            match = re.match(r"【(S\d+)】", first_line)
            if match:
                speaker = match.group(1)
                segments.append((speaker, text.strip()))

    # Build speaker sequence
    seq = [s[0] for s in segments]

    # Count speakers
    speakers = set(s[0] for s in segments)
    result.speaker_count = len(speakers)
    result.segments = segments
    result.seq = seq

    # Calculate speaker balance (rough estimate based on segment count)
    total_segments = len(segments)
    s1_count = sum(1 for s in segments if s[0] == "S1")
    s2_count = sum(1 for s in segments if s[0] == "S2")
    result.balance_s1 = s1_count / total_segments if total_segments > 0 else 0
    result.balance_s2 = s2_count / total_segments if total_segments > 0 else 0

    return result


def damerau_levenshtein(a: List[str], b: List[str]) -> int:
    """Compute the Damerau-Levenshtein distance between two sequences."""
    n, m = len(a), len(b)
    if n == 0:
        return m
    if m == 0:
        return n

    d = [[0] * (m + 1) for _ in range(n + 1)]
    for i in range(n + 1):
        d[i][0] = i
    for j in range(m + 1):
        d[0][j] = j

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            cost = 0 if a[i - 1] == b[j - 1] else 1
            d[i][j] = min(
                d[i - 1][j] + 1,       # deletion
                d[i][j - 1] + 1,       # insertion
                d[i - 1][j - 1] + cost  # substitution
            )
            if i > 1 and j > 1 and a[i - 1] == b[j - 2] and a[i - 2] == b[j - 1]:
                d[i][j] = min(d[i][j], d[i - 2][j - 2] + cost)  # transposition

    return d[n][m]


def normalize_sequence(seq: List[str]) -> List[str]:
    """Normalize speaker sequence: merge consecutive same-speaker runs."""
    if not seq:
        return []
    normalized = [seq[0]]
    for s in seq[1:]:
        if s != normalized[-1]:
            normalized.append(s)
    return normalized


def evaluate(result: TuneResult) -> float:
    """Evaluate the diarization quality and return a score (0-100)."""
    score = 0.0
    details = []

    # 1. Speaker count (40 pts)
    if result.speaker_count == 2:
        score += 40
        details.append(f"speakers=2 ✓ (+40)")
    elif result.speaker_count == 1:
        details.append(f"speakers=1 ✗ (+0)")
    else:
        score += 10
        details.append(f"speakers={result.speaker_count} (+10, expected 2)")

    # 2. Speaker balance (20 pts)
    if result.speaker_count == 2:
        s1_pct = min(result.balance_s1, result.balance_s2)
        s2_pct = max(result.balance_s1, result.balance_s2)
        if s1_pct >= 0.2:
            score += 20
            details.append(f"balance S1={result.balance_s1:.0%} S2={result.balance_s2:.0%} ✓ (+20)")
        elif s1_pct >= 0.1:
            score += 10
            details.append(f"balance S1={result.balance_s1:.0%} S2={result.balance_s2:.0%} ⚠ (+10)")
        else:
            details.append(f"balance S1={result.balance_s1:.0%} S2={result.balance_s2:.0%} ✗ (+0)")

    # 3. Segment count (20 pts) — compare to ground truth
    gt_norm = normalize_sequence(GROUND_TRUTH_SEQ)
    detected_norm = normalize_sequence(result.seq)
    gt_seg_count = len(gt_norm)
    detected_seg_count = len(detected_norm)

    if detected_seg_count >= gt_seg_count * 0.3 and detected_seg_count <= gt_seg_count * 1.5:
        score += 20
        details.append(f"segments={detected_seg_count} (gt={gt_seg_count}) ✓ (+20)")
    elif detected_seg_count >= gt_seg_count * 0.2 and detected_seg_count <= gt_seg_count * 2.0:
        score += 10
        details.append(f"segments={detected_seg_count} (gt={gt_seg_count}) ⚠ (+10)")
    else:
        details.append(f"segments={detected_seg_count} (gt={gt_seg_count}) ✗ (+0)")

    # 4. Sequence similarity (20 pts) — compare normalized sequences
    if result.speaker_count == 2 and detected_seg_count > 0:
        # Align: compare detected vs ground truth at the normalized level
        gt_norm = normalize_sequence(GROUND_TRUTH_SEQ)
        detected_norm = normalize_sequence(result.seq)

        # Take the first N segments for comparison
        min_len = min(len(gt_norm), len(detected_norm))
        if min_len > 0:
            dist = damerau_levenshtein(gt_norm[:min_len], detected_norm[:min_len])
            max_dist = min_len
            similarity = 1.0 - (dist / max_dist)
            seq_score = similarity * 20
            score += seq_score
            details.append(f"seq_similarity={similarity:.0%} (+{seq_score:.0f})")
        else:
            details.append(f"seq_similarity=N/A (+0)")

    result.score = score
    result.details = " | ".join(details)
    return score


def run_trial(params: dict) -> Optional[TuneResult]:
    """Run a single trial with the given parameters."""
    print(f"\n  Config: threshold={params['clustering_threshold']}, "
          f"minSeg={params['embedding_minSegmentDuration']}, "
          f"minOn={params['segmentation_minDurationOn']}, "
          f"minOff={params['segmentation_minDurationOff']}, "
          f"onset={params['segmentation_speechOnsetThreshold']}, "
          f"stepRatio={params['segmentation_stepRatio']}")

    # Generate and write config
    config_body = build_config(params)
    write_diarizer_swift(config_body)

    # Build
    build_time = build_project()
    if build_time < 0:
        return None

    # Run
    print(f"  Build: {build_time:.1f}s, Running diarization...", end="", flush=True)
    run_start = time.time()
    output = run_diarization()
    run_time = time.time() - run_start

    if output is None:
        return None

    print(f" {run_time:.1f}s", flush=True)

    # Parse and evaluate
    result = parse_diarization_output(output)
    result.params = params
    result.build_time = build_time
    result.run_time = run_time

    return result


def main():
    print("=" * 70)
    print("AutoResearch: FluidAudio Diarization Parameter Tuner")
    print("=" * 70)
    print(f"\nAudio: {AUDIO_FILE}")
    print(f"Ground truth: {GT_COUNT} speaker segments, "
          f"{len(normalize_sequence(GROUND_TRUTH_SEQ))} normalized turns")
    print(f"\nParameter space: {len(PARAM_GRID)} dimensions")

    # Calculate total combinations
    total = 1
    for name, values in PARAM_GRID.items():
        total *= len(values)
        print(f"  {name}: {values}")

    print(f"\nTotal combinations: {total}")
    print(f"Estimated time: {total * 10:.0f}s ({total * 10 / 60:.1f} min)")

    if total > 200:
        print("\n⚠ Large search space. Using smart sampling instead of full grid.")
        print("  Phase 1: Coarse grid (vary one parameter at a time)")
        print("  Phase 2: Refine around best values")
        print("  Phase 3: Fine-tune top combinations")
        smart_search = True
    else:
        smart_search = False

    # ── Phase 1: Baseline ──
    print("\n" + "=" * 70)
    print("Phase 1: Baseline (default config)")
    print("=" * 70)
    baseline_params = {
        "clustering_threshold": 0.5,
        "embedding_minSegmentDuration": 0.5,
        "segmentation_minDurationOn": 0.2,
        "segmentation_minDurationOff": 0.3,
        "segmentation_speechOnsetThreshold": 0.5,
        "segmentation_speechOffsetThreshold": 0.5,
        "postProcessing_minGap": 0.05,
        "segmentation_stepRatio": 0.2,
        "clustering_warmStartFa": 0.07,
        "clustering_warmStartFb": 0.8,
    }
    result = run_trial(baseline_params)
    if result:
        score = evaluate(result)
        print(f"  Score: {score:.1f}/100")
        print(f"  Details: {result.details}")
        print(f"  Speaker count: {result.speaker_count}")
        print(f"  Segments: {len(result.seq)}")
        print(f"  Balance: S1={result.balance_s1:.0%}, S2={result.balance_s2:.0%}")
        if result.seq:
            print(f"  Sequence: {result.seq[:20]}{'...' if len(result.seq) > 20 else ''}")
    else:
        print("  BASELINE FAILED — aborting")
        sys.exit(1)

    # ── Phase 2: Coarse sweep — vary one parameter at a time ──
    print("\n" + "=" * 70)
    print("Phase 2: One-at-a-time sweep")
    print("=" * 70)

    best_score = score
    best_params = baseline_params.copy()
    best_result = result

    param_order = [
        "clustering_threshold",
        "embedding_minSegmentDuration",
        "segmentation_minDurationOn",
        "segmentation_minDurationOff",
        "segmentation_speechOnsetThreshold",
        "segmentation_stepRatio",
        "postProcessing_minGap",
        "clustering_warmStartFa",
        "clustering_warmStartFb",
    ]

    for param_name in param_order:
        values = PARAM_GRID[param_name]
        param_best_score = best_score
        param_best_value = best_params[param_name]

        for val in values:
            # Skip the current best value
            if abs(val - best_params[param_name]) < 1e-6:
                continue

            trial_params = best_params.copy()
            trial_params[param_name] = val

            result = run_trial(trial_params)
            if not result:
                continue

            score = evaluate(result)
            print(f"  {param_name}={val}: score={score:.1f} | {result.details}")

            if score > param_best_score:
                param_best_score = score
                param_best_value = val

        if param_best_value != best_params[param_name]:
            print(f"  >>> {param_name} improved: {best_params[param_name]} → {param_best_value} "
                  f"(score {best_score:.1f} → {param_best_score:.1f})")
            best_params[param_name] = param_best_value
            best_score = param_best_score

    # ── Phase 3: Second pass around best values ──
    print("\n" + "=" * 70)
    print("Phase 3: Fine-tune around best values")
    print("=" * 70)

    for param_name in param_order:
        values = PARAM_GRID[param_name]
        current_val = best_params[param_name]

        # Find nearest neighbors
        sorted_vals = sorted(values)
        idx = sorted_vals.index(current_val) if current_val in sorted_vals else -1

        neighbors = []
        if idx > 0:
            neighbors.append(sorted_vals[idx - 1])
        if idx < len(sorted_vals) - 1:
            neighbors.append(sorted_vals[idx + 1])

        for val in neighbors:
            trial_params = best_params.copy()
            trial_params[param_name] = val

            result = run_trial(trial_params)
            if not result:
                continue

            score = evaluate(result)
            print(f"  {param_name}={val}: score={score:.1f} | {result.details}")

            if score > best_score:
                print(f"  >>> Improved! {param_name}: {current_val} → {val}")
                best_params[param_name] = val
                best_score = score

    # ── Final: Run with best params ──
    print("\n" + "=" * 70)
    print("FINAL: Best parameters")
    print("=" * 70)
    print(f"\nScore: {best_score:.1f}/100")
    print(f"\nParameters:")
    for k, v in best_params.items():
        print(f"  {k}: {v}")

    print(f"\nSpeaker count: {best_result.speaker_count}")
    print(f"Sequence: {best_result.seq[:15]}{'...' if len(best_result.seq) > 15 else ''}")
    print(f"Details: {best_result.details}")

    # Save best params
    with open(os.path.join(PROJECT_DIR, "best_params.json"), "w") as f:
        json.dump({"score": best_score, "params": best_params}, f, indent=2)
    print(f"\nBest params saved to {PROJECT_DIR}/best_params.json")


if __name__ == "__main__":
    main()