// Auto-generated by make — do not edit
let buildVersion = "0.1.6"
let buildCommit = "7806c75"
let buildBranch = "main"
let buildDate = "2026-04-15 12:46:22 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
