// ============================================================================
// Server.swift — OpenAI-compatible HTTP server for transcription
// Part of ohr — On-device speech-to-text from the command line
// ============================================================================

import Foundation
import Hummingbird
import OhrCore

/// Server configuration passed from CLI argument parsing.
struct ServerConfig: Sendable {
    let host: String
    let port: Int
    let cors: Bool
    let maxConcurrent: Int
    let debug: Bool
    let allowedOrigins: [String]
    let originCheckEnabled: Bool
    let token: String?
    let tokenWasAutoGenerated: Bool
    let publicHealth: Bool

    var healthRequiresAuthentication: Bool {
        token != nil && !publicHealth && !isLoopbackHost(host)
    }
}

/// Shared server state accessible by all request handlers.
final class ServerState: Sendable {
    let logStore: LogStore
    let semaphore: AsyncSemaphore
    let config: ServerConfig

    init(config: ServerConfig) {
        self.logStore = LogStore(capacity: 1000)
        self.semaphore = AsyncSemaphore(value: config.maxConcurrent)
        self.config = config
    }
}

/// Global server state — set once at startup, read by handlers.
nonisolated(unsafe) var serverState: ServerState!

/// Retry helper for semaphore timeout.
struct SemaphoreTimeoutError: Error, LocalizedError {
    var errorDescription: String? { "Request queued too long — server at max concurrent capacity" }
}

/// Async semaphore for limiting concurrent operations.
actor AsyncSemaphore {
    private var count: Int
    private var waiters: [(id: UUID, continuation: CheckedContinuation<Void, any Error>)] = []

    init(value: Int) {
        self.count = value
    }

    func wait(timeout: Duration = .seconds(30)) async throws {
        if count > 0 {
            count -= 1
            return
        }

        let id = UUID()
        try await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, any Error>) in
            waiters.append((id: id, continuation: cont))
            Task { [weak self] in
                try? await Task.sleep(for: timeout)
                await self?.timeoutWaiter(id: id)
            }
        }
    }

    private func timeoutWaiter(id: UUID) {
        if let idx = waiters.firstIndex(where: { $0.id == id }) {
            let waiter = waiters.remove(at: idx)
            waiter.continuation.resume(throwing: SemaphoreTimeoutError())
        }
    }

    func signal() {
        if let waiter = waiters.first {
            waiters.removeFirst()
            waiter.continuation.resume()
        } else {
            count += 1
        }
    }
}

/// Start the OpenAI-compatible HTTP server for transcription.
func startServer(config: ServerConfig) async throws {
    serverState = ServerState(config: config)
    let router = Router()

    // Security middleware
    router.add(middleware: SecurityMiddleware<BasicRequestContext>(config: config))

    // Health
    router.get("/health") { _, _ -> Response in
        let active = await serverState.logStore.activeRequests
        let available = isSpeechAvailable()
        let langs = await speechSupportedLocales()
        let health: [String: Any] = [
            "status": available ? "ok" : "model_unavailable",
            "model": modelName,
            "version": version,
            "active_requests": active,
            "model_available": available,
            "supported_formats": AudioFormat.allSupported,
            "supported_languages": langs
        ]
        if let data = try? JSONSerialization.data(withJSONObject: health, options: [.sortedKeys]),
           let json = String(data: data, encoding: .utf8) {
            return jsonResponse(json)
        }
        return jsonResponse("{\"status\":\"ok\"}")
    }

    // Models
    router.get("/v1/models") { _, _ -> Response in
        let langs = await speechSupportedLocales()
        return jsonResponse(jsonString(ModelsListResponse(
            object: "list",
            data: [.init(
                id: modelName, object: "model", created: 1719792000, owned_by: "apple",
                supported_formats: AudioFormat.allSupported,
                supported_response_formats: ["json", "text", "srt", "verbose_json", "vtt"],
                notes: "Apple on-device speech-to-text via SpeechAnalyzer. Supported languages: \(langs.prefix(10).joined(separator: ", "))\(langs.count > 10 ? " (\(langs.count) total)" : "")"
            )]
        )))
    }

    // Transcription endpoint
    router.post("/v1/audio/transcriptions") { request, context -> Response in
        let start = Date()
        let requestId = "trans-\(UUID().uuidString.prefix(12).lowercased())"

        // Acquire semaphore
        do {
            try await serverState.semaphore.wait(timeout: .seconds(30))
        } catch {
            let log = RequestLog(
                id: requestId, timestamp: ISO8601DateFormatter().string(from: Date()),
                method: "POST", path: "/v1/audio/transcriptions", status: 429,
                duration_ms: Int(Date().timeIntervalSince(start) * 1000),
                estimated_tokens: nil, error: "Too many concurrent requests",
                request_body: nil, response_body: nil, events: ["semaphore timeout"]
            )
            await serverState.logStore.append(log)
            return openAIError(status: .tooManyRequests, message: "Server at max concurrent capacity (\(config.maxConcurrent)). Try again later.", type: "rate_limit_error")
        }

        await serverState.logStore.requestStarted()

        let result: (response: Response, trace: TranscriptionTrace)
        do {
            result = try await handleTranscription(request, context: context)
        } catch {
            await serverState.semaphore.signal()
            await serverState.logStore.requestFinished()
            throw error
        }
        await serverState.semaphore.signal()
        await serverState.logStore.requestFinished()

        // Log
        let durationMs = Int(Date().timeIntervalSince(start) * 1000)
        let log = RequestLog(
            id: requestId,
            timestamp: ISO8601DateFormatter().string(from: start),
            method: "POST", path: "/v1/audio/transcriptions",
            status: result.response.status == .ok ? 200 : result.response.status.code,
            duration_ms: durationMs,
            estimated_tokens: nil,
            error: result.trace.error,
            request_body: nil,
            response_body: nil,
            events: result.trace.events
        )
        await serverState.logStore.append(log)

        return result.response
    }

    // Logs query (debug only)
    router.get("/v1/logs") { request, _ -> Response in
        guard serverState.config.debug else {
            return openAIError(status: .notFound, message: "Request logs are only available with --debug.", type: "invalid_request_error")
        }
        let queryString = request.uri.query ?? ""
        let params = parseQueryParams(queryString)
        let statusFilter = params["status"].flatMap(Int.init)
        let pathFilter = params["path"]
        let errorsOnly = params["errors"] == "true"
        let rawLimit = params["limit"].flatMap(Int.init) ?? 50
        let limit = min(max(rawLimit, 1), 1000)
        let sinceDate = params["since"].flatMap { ISO8601DateFormatter().date(from: $0) }

        let logs = await serverState.logStore.query(
            status: statusFilter, path: pathFilter,
            errorsOnly: errorsOnly, since: sinceDate, limit: limit
        )
        return jsonResponse(jsonString(LogListResponse(object: "list", count: logs.count, data: logs)))
    }

    // Logs stats (debug only)
    router.get("/v1/logs/stats") { _, _ -> Response in
        guard serverState.config.debug else {
            return openAIError(status: .notFound, message: "Request log stats are only available with --debug.", type: "invalid_request_error")
        }
        let stats = await serverState.logStore.stats(maxConcurrent: config.maxConcurrent)
        return jsonResponse(jsonString(stats))
    }

    // Stub endpoints
    router.post("/v1/chat/completions") { _, _ -> Response in
        openAIError(status: .init(code: 501), message: "Chat completions not supported. Use POST /v1/audio/transcriptions.", type: "invalid_request_error")
    }
    router.post("/v1/embeddings") { _, _ -> Response in
        openAIError(status: .init(code: 501), message: "Embeddings not supported. Use POST /v1/audio/transcriptions.", type: "invalid_request_error")
    }

    let app = Application(
        router: router,
        configuration: .init(address: .hostname(config.host, port: config.port))
    )

    // Banner
    let originStatus = config.originCheckEnabled
        ? "localhost only (\(config.allowedOrigins.joined(separator: ", ")))"
        : styled("disabled (all origins allowed)", .red)
    var bannerLines = [
        "\(styled("ohr server", .cyan, .bold)) v\(version)",
        "\(styled("├", .dim)) endpoint: http://\(config.host):\(config.port)",
        "\(styled("├", .dim)) model:    \(modelName)",
        "\(styled("├", .dim)) cors:     \(config.cors ? "enabled" : "disabled")",
        "\(styled("├", .dim)) origin:   \(originStatus)",
        "\(styled("├", .dim)) token:    \(config.token != nil ? "required" : "none")",
        "\(styled("├", .dim)) health:   \(config.healthRequiresAuthentication ? "auth required" : "public")",
        "\(styled("├", .dim)) max concurrent: \(config.maxConcurrent)",
        "\(styled("├", .dim)) debug:    \(config.debug ? "on" : "off")",
    ]
    if config.tokenWasAutoGenerated, let token = config.token {
        bannerLines.append("\(styled("├", .dim)) \(styled("token:", .yellow)) \(token)")
    }
    if !config.originCheckEnabled && config.cors {
        bannerLines.append("\(styled("├", .dim)) \(styled("WARNING: --footgun mode - no origin check + CORS enabled", .red, .bold))")
    }
    bannerLines.append("\(styled("└", .dim)) ready")
    printStderr(bannerLines.joined(separator: "\n"))

    printStderr("")
    printStderr(styled("Endpoints:", .yellow, .bold))
    printStderr("  POST http://\(config.host):\(config.port)/v1/audio/transcriptions")
    printStderr("  GET  http://\(config.host):\(config.port)/v1/models")
    if config.debug {
        printStderr("  GET  http://\(config.host):\(config.port)/v1/logs")
        printStderr("  GET  http://\(config.host):\(config.port)/v1/logs/stats")
    }
    printStderr("  GET  http://\(config.host):\(config.port)/health")
    printStderr("")

    try await app.run()
}

func isLoopbackHost(_ host: String) -> Bool {
    switch host.lowercased() {
    case "127.0.0.1", "localhost", "::1", "[::1]": return true
    default: return false
    }
}

func parseQueryParams(_ query: String) -> [String: String] {
    var params: [String: String] = [:]
    for pair in query.split(separator: "&") {
        let parts = pair.split(separator: "=", maxSplits: 1)
        if parts.count == 2 {
            let key = String(parts[0]).removingPercentEncoding ?? String(parts[0])
            let value = String(parts[1]).removingPercentEncoding ?? String(parts[1])
            params[key] = value
        }
    }
    return params
}

func jsonResponse(_ body: String, status: HTTPResponse.Status = .ok) -> Response {
    var headers = HTTPFields()
    headers[.contentType] = "application/json"
    return Response(status: status, headers: headers, body: .init(byteBuffer: .init(string: body)))
}

func openAIError(status: HTTPResponse.Status, message: String, type: String) -> Response {
    let error = OpenAIErrorResponse(error: .init(message: message, type: type, param: nil, code: nil))
    return jsonResponse(jsonString(error), status: status)
}
